# Data source configuration
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # Main library Data source
            master:
                url: jdbc:mysql://localhost:3306/store4?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 1234
            # Data source from library
            slave:
                # From Data source switch / default off
                enabled: false
                url:
                username:
                password:
            # initial number of connections
            initialSize: 5
            # Minimum number of connection pools
            minIdle: 10
            # Maximum number of connection pools
            maxActive: 20
            # Configure the time to wait for a timeout to get a connection
            maxWait: 60000
            # Configure how long the interval is to perform detection and detect idle connections that need to be closed, in milliseconds
            timeBetweenEvictionRunsMillis: 60000
            # Configure the minimum lifetime of a connection in the pool, in milliseconds
            minEvictableIdleTimeMillis: 300000
            # Configure the maximum lifetime of a connection in the pool, in milliseconds
            maxEvictableIdleTimeMillis: 900000
            # Configure to detect whether the connection is valid
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # Set a whitelist, if not filled, all access will be allowed
                allow:
                url-pattern: /druid/*
                # Console management User name and password
                login-username: store
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # slow SQL logging
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
